#!/usr/bin/env bash

[[ ! -d "$HOME/bin" ]] && mkdir $HOME/bin
rm -f $HOME/.amu_config
rm -f $HOME/.rubyripper_settings_orig
rm -f $HOME/bin/import-cd
rm -f $HOME/bin/import-bandcamp-flac-release
rm -f $HOME/bin/rename_bandcamp_release.py
rm -f $HOME/bin/add_mix
rm -f $HOME/bin/add_radio
rm -f $HOME/bin/list_label_releases
rm -f $HOME/bin/filter_unique_releases
rm -f $HOME/bin/zip_release
rm -f $HOME/bin/import-bleep-wav-release
rm -f $HOME/bin/import-greedbag-wav-release
rm -f $HOME/bin/import-greedbag-mp3-release
rm -f $HOME/bin/list-media-durations
ln -f ./amu/.amu_config $HOME/.amu_config
ln -f ./amu/.rubyripper_settings_orig $HOME/.rubyripper_settings_orig
ln -f ./amu/import-cd $HOME/bin/import-cd
ln -f ./amu/import-bandcamp-flac-release $HOME/bin/import-bandcamp-flac-release
ln -f ./amu/rename_bandcamp_release.py $HOME/bin/rename_bandcamp_release.py
ln -f ./amu/add_mix $HOME/bin/add_mix
ln -f ./amu/add_radio $HOME/bin/add_radio
ln -f ./amu/list_label_releases $HOME/bin/list_label_releases
ln -f ./amu/filter_unique_releases $HOME/bin/filter_unique_releases
ln -f ./amu/zip_release $HOME/bin/zip_release
ln -f ./amu/import-bleep-wav-release $HOME/bin/import-bleep-wav-release
ln -f ./amu/import-greedbag-wav-release $HOME/bin/import-greedbag-wav-release
ln -f ./amu/import-greedbag-mp3-release $HOME/bin/import-greedbag-mp3-release
ln -f ./amu/list-media-durations $HOME/bin/list-media-durations
