#!/usr/bin/env bash

shopt -s nullglob
playlist_duration_ms=0
for song_file in *.{mp3,ogg,m4a,flac,wav}; do
    playlist_duration_ms=$(expr $playlist_duration_ms + $(mediainfo --Inform="Audio;%Duration%" "$song_file"))
    track_duration_ms=$(mediainfo --Inform="Audio;%Duration%" "$song_file")
    track_duration_secs=$(expr $track_duration_ms / 1000)
    track_duration_mins=$(expr $track_duration_ms / 60000)
    track_duration_remaining_secs=$(expr $track_duration_secs - $(expr $track_duration_mins \* 60))
    echo "$song_file - $track_duration_mins:$track_duration_remaining_secs"
done
shopt -u nullglob

playlist_duration_secs=$(expr $playlist_duration_ms / 1000)
playlist_duration_mins=$(expr $playlist_duration_ms / 60000)
playlist_duration_remaining_secs=$(expr $playlist_duration_secs - $(expr $playlist_duration_mins \* 60))

echo
echo "Total duration: $playlist_duration_mins:$playlist_duration_remaining_secs"
