#!/usr/bin/env bash

label_id=$1

function get_number_of_pages() {
    last_page=$(curl https://api.discogs.com/labels/$label_id/releases?per_page=100 --user-agent "amu/0.1" -H "Authorization: Discogs key=ujteSPrEAXsVvqTWrRiU, secret=XSglsnOKXACMLbhaAiVbhYVwJJbANMAV" | jq '.pagination["pages"]')
    echo $last_page
}

function get_all_releases() {
    rm -rf /tmp/list.txt
    for ((i=1; i<=$last_page; i++))
    do
        echo "Getting page $i"
        curl -s "https://api.discogs.com/labels/$label_id/releases?page=$i&per_page=100" --user-agent "amu/0.1" -H "Authorization: Discogs key=ujteSPrEAXsVvqTWrRiU, secret=XSglsnOKXACMLbhaAiVbhYVwJJbANMAV" \
        | jq '.releases[] | {catno: .catno, artist: .artist, title: .title, year: .year, format: .format}' \
        | paste -s \
        | tr "{" " " \
        | tr "}" "\n" \
        | sed -e 's/^[ \t]*//' \
        | sed -e '/\"format\":.*RE/d' \
        | sed -e '/\"format\":.*RP/d' \
        | sed -e 's/[[:space:]]\+/ /g' \
        | uniq >> /tmp/list.txt
    done
}

get_number_of_pages
get_all_releases
