#!/usr/bin/env bash

if [ ! -d "$USER_HOME/.config/powerline" ]
then
	pip install --user git+https://github.com/Lokaltog/powerline
	mkdir -p ~/.config/powerline
	cp -R ~/.local/lib/python2.7/site-packages/powerline/config_files/* ~/.config/powerline
	rm -f ~/.config/powerline/config.json
	ln -f ./powerline/config.json ~/.config/powerline/config.json
	ln -f ./powerline/jacderida-shell.json ~/.config/powerline/themes/shell/jacderida.json
else
    echo -e "${green}Already bootstrapped powerline${nc}"
fi
