#!/usr/bin/env bash

if [ ! -d "~/.vim/colors" ]; then
	mkdir -p ~/.vim/colors
fi
if [ ! -d "~/.vim/autoload" ]; then
	mkdir -p ~/.vim/autoload
fi
if [ ! -d "~/.vim/bundle" ]; then
	mkdir -p ~/.vim/bundle
fi

rm -f ~/.vimrc
ln -f ./vim/.vimrc ~/.vimrc
cp ./vim/colors/*.* ~/.vim/colors
cp ./vim/pathogen.vim ~/.vim/autoload
if [ ! -d "~/.vim/bundle/vim-json" ]; then
	git clone https://github.com/elzr/vim-json.git ~/.vim/bundle/vim-json
fi
if [ ! -d "~/.vim/bundle/vim-rails" ]; then
	git clone git://github.com/tpope/vim-rails.git ~/.vim/bundle/vim-rails
fi
if [ ! -d "~/.vim/bundle/vim-bundler" ]; then
	git clone git://github.com/tpope/vim-bundler.git ~/.vim/bundle/vim-bundler
fi
