#!/usr/bin/env bash

echo -e "${green}Setting up solarized for gnome-terminal${nc}"
source ./gnome-terminal/solarized/set_dark.sh
cp ./gnome-terminal/dircolors.ansi-dark ~/.dircolors
eval `dircolors ~/.dircolors`
