#!/usr/bin/env bash

operating_system=$(uname -s)
if [[ $operating_system != "Darwin" && $operating_system != CYGWIN_NT-* ]]; then
    echo -e "${green}Setting up solarized for gnome-terminal${nc}"
    source ./gnome-terminal/solarized/set_dark.sh
    cp ./gnome-terminal/dircolors.ansi-dark ~/.dircolors
    cp ./gnome-terminal/dircolors.ansi-light ~/.dircolors
    eval `dircolors ~/.dircolors`
    if [[ ! -d "$HOME/dev/base16-gnome-terminal" ]]; then
        present_directory=$(pwd)
        cd $HOME/dev
        git clone https://github.com/chriskempson/base16-gnome-terminal
        cd $present_directory
    fi
fi
