#!/usr/bin/env bash

[[ ! -d "$HOME/.i3" ]] && mkdir $HOME/.i3
rm -f $HOME/.i3/config
ln -f ./i3/config $HOME/.i3/config
rm -f $HOME/.i3blocks/config
ln -f ./i3/i3blocks-config $HOME/.i3blocks/config
