#!/usr/bin/env bash

if [ ! -d "$HOME/.subversion" ]
then
	mkdir -p $HOME/.subversion
	ln -f ./subversion/config ~/.subversion/config
else
    echo -e "${green}Already bootstrapped subversion config${nc}"
fi
