#!/usr/bin/env bash

function update_font_cache() {
    operating_system=$(uname -a)
    case $operating_system in
        *Ubuntu*)
            fc-cache -vf $HOME/.fonts
            ;;
        *)
            echo "Updating font cache not supported on $operating_system. Please add a case to update_font_cache for $operating_system ."
            exit 1
    esac
}

function install_patched_fonts() {
    [[ ! -d "$HOME/.fonts" ]] && mkdir $HOME/.fonts
    present_directory=$(pwd)
    cd $HOME/dev
    git clone https://github.com/Lokaltog/powerline-fonts.git
    cd $HOME/dev/powerline-fonts
    find . -name "*.otf" -exec cp {} $HOME/.fonts \; -o -name "*.ttf" -exec cp {} $HOME/.fonts \;
}
if [ ! -d "$USER_HOME/.fonts" ]; then
	mkdir ~/.fonts
fi

find ./fonts -type f -iname "*.ttf" -print0 | while IFS= read -r -d $'\0' line; do
    echo -e "${green}Installing $line font${nc}"
    cp $line ~/.fonts
done

find ./fonts -type f -iname "*.otf" -print0 | while IFS= read -r -d $'\0' line; do
    echo -e "${green}Installing $line font${nc}"
    cp $line ~/.fonts
done

install_patched_fonts
