#!/usr/bin/env bash

if [ ! -d "$USER_HOME/.fonts" ]; then
	mkdir ~/.fonts
fi

find ./fonts -type f -iname "*.ttf" -print0 | while IFS= read -r -d $'\0' line; do
    cp $line ~/.fonts
done

find ./fonts -type f -iname "*.otf" -print0 | while IFS= read -r -d $'\0' line; do
    cp $line ~/.fonts
done
