#!usr/bin/env bash

if [ ! -e "/usr/local/bin/aws" ]
then
    mkdir ~/dev/aws-cli
    git clone https://github.com/aws/aws-cli.git ~/dev/aws-cli
    present_directory=`pwd`
    cd ~/dev/aws-cli
    git pull origin master
    sudo python setup.py install
    complete -C aws_completer aws
    cd $present_directory
else
    echo -e "${green}Already bootstrapped aws-cli${nc}"
fi
