#!usr/bin/env bash

set -e

function set_aws_cli_credentials
{
    if [[ -n "$AWS_ACCESS_KEY_ID" && -n "$AWS_ACCESS_KEY" ]]
    then
        echo -e "${green}Setting up config for aws-cli${nc}"
        if [ ! -d "$HOME/.aws/" ]; then
            mkdir ~/.aws
        fi
        cp ./aws/config ~/.aws/config
        # It's more common to use / as the delimiting character with sed, but this causes
        # problems, because the aws secret key contains a / character.
        sed -i ~/.aws/config -e "s#AWS_ACCESS_KEY_ID#$AWS_ACCESS_KEY_ID#g"
        sed -i ~/.aws/config -e "s#AWS_ACCESS_KEY#$AWS_ACCESS_KEY#g"
    fi
}

function set_s3cmd_credentials
{
    if [[ -n "$AWS_ACCESS_KEY_ID" && -n "$AWS_ACCESS_KEY" ]]; then
        echo -e "${green}Setting up config for s3cmd${nc}"
        cp ./aws/s3cfg ~/.s3cfg
        sed -i ~/.s3cfg -e "s#AWS_ACCESS_KEY_ID#$AWS_ACCESS_KEY_ID#g"
        sed -i ~/.s3cfg -e "s#AWS_ACCESS_KEY#$AWS_ACCESS_KEY#g"
    fi
}

set_aws_cli_credentials
set_s3cmd_credentials
