#!/usr/bin/env bash

echo -e "${green}Removing netbeans.conf and linking from dotfiles${nc}"
sudo rm /usr/local/netbeans-7.4/etc/netbeans.conf
sudo ln ./netbeans/netbeans.conf /usr/local/netbeans-7.4/etc/netbeans.conf
