#!/usr/bin/env bash

[[ ! -d "$HOME/.config/terminator" ]] && mkdir -p $HOME/.config/terminator
rm -f $HOME/.config/terminator/config
ln -f ./terminator/config $HOME/.config/terminator/config
rm -f $HOME/.config/terminator/gruvbox_256palette.sh
ln -f ./terminator/gruvbox_256palette.sh $HOME/.config/terminator/gruvbox_256palette.sh
