#!/usr/bin/env bash

if [[ ! -d "$HOME/.mpd" ]]; then
    mkdir -p $HOME/.mpd/playlists
    touch $HOME/.mpd/{database,log,pid,state}
fi

[[ ! -d "$HOME/.mpdsribble" ]] && mkdir $HOME/.mpdsribble

rm -f $HOME/.mpd/mpd.conf
rm -f $HOME/.mpdsribble/mpdsribble.conf
ln -f ./mpd/mpd.conf $HOME/.mpd/mpd.conf
ln -f ./mpd/mpdsribble.conf $HOME/.mpdsribble/mpdsribble.conf
