#!/usr/bin/env bash

if [[ ! -d "$HOME/.mpd" ]]; then
    mkdir -p $HOME/.mpd/playlists
    touch $HOME/.mpd/{database,log,pid,state}
fi

[[ ! -d "$HOME/.mpdsribble" ]] && mkdir $HOME/.mpdscribble
[[ ! -d "$HOME/.ncmpcpp" ]] && mkdir $HOME/.ncmpcpp
[[ ! -d "$HOME/bin" ]] && mkdir $HOME/bin

rm -f $HOME/.mpd/mpd.conf
rm -f $HOME/.mpdscribble/mpdscribble.conf
rm -f $HOME/.ncmpcpp/config
ln -f ./mpd/mpd.conf $HOME/.mpd/mpd.conf
ln -f ./mpd/mpdscribble.conf $HOME/.mpdscribble/mpdscribble.conf
ln -f ./mpd/ncmpcpp $HOME/.ncmpcpp/config
ln -f ./mpd/start_mpd.sh $HOME/bin/start_mpd.sh
