#!/usr/bin/env bash

echo -e "${green}Removing current .bashrc, .bash_profile and .profile, and linking from dotfiles.${nc}"
rm -f ~/.bashrc
ln -f ./bash/.bashrc ~/.bashrc
rm -f ~/.bash_profile
ln -f ./bash/.bash_profile ~/.bash_profile
rm -f ~/.bash_aliases
ln -f ./bash/.bash_aliases ~/.bash_aliases
rm -f ~/.profile
ln -f ./bash/.profile ~/.profile

# It turns out this won't work at all on Cygwin, as it doesn't have full glibc emulation (or something along those lines), nor can it use LD_PRELOAD.
if [ $(uname -s) != "CYGWIN_NT-6.1" ]; then
    if [ ! -d "$HOME/dev/stderred" ]
    then
        # Makes error output red in the console
        present_directory=`pwd`
        cd ~/dev
        git clone https://github.com/sickill/stderred.git
        cd stderred
        make
        cd $present_directory
    else
        echo -e "${green}Already bootstrapped stderred plugin"
    fi
fi
