#!/usr/bin/env bash

echo -e "${green}Removing current .bashrc, .bash_profile and .profile, and linking from dotfiles.${nc}"
rm -f ~/.bashrc
ln -f ./bash/.bashrc ~/.bashrc
rm -f ~/.bash_profile
ln -f ./bash/.bash_profile ~/.bash_profile
rm -f ~/.aliases
ln -f ./bash/.bash_aliases ~/.aliases
rm -f ~/.profile
ln -f ./bash/.profile ~/.profile

if [[ ! -d "$HOME/bin" ]]; then
    mkdir "$HOME/bin"
    cp ./bash/colourtest $HOME/bin/colourtest
    cp ./bash/print_colour_palette $HOME/bin/print_colour_palette
fi
